/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.sohlman.ddmfieldattribute.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DDMFieldAttribute service. Represents a row in the &quot;DDMFA_DDMFieldAttribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.sohlman.ddmfieldattribute.model.impl.DDMFieldAttributeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.sohlman.ddmfieldattribute.model.impl.DDMFieldAttributeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDMFieldAttribute
 * @generated
 */
@ProviderType
public interface DDMFieldAttributeModel extends BaseModel<DDMFieldAttribute> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ddm field attribute model instance should use the {@link DDMFieldAttribute} interface instead.
	 */

	/**
	 * Returns the primary key of this ddm field attribute.
	 *
	 * @return the primary key of this ddm field attribute
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ddm field attribute.
	 *
	 * @param primaryKey the primary key of this ddm field attribute
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ddm field attribute ID of this ddm field attribute.
	 *
	 * @return the ddm field attribute ID of this ddm field attribute
	 */
	public long getDdmFieldAttributeId();

	/**
	 * Sets the ddm field attribute ID of this ddm field attribute.
	 *
	 * @param ddmFieldAttributeId the ddm field attribute ID of this ddm field attribute
	 */
	public void setDdmFieldAttributeId(long ddmFieldAttributeId);

	@Override
	public DDMFieldAttribute cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}